// Code generated by astool. DO NOT EDIT.

package streams

import (
	typeemoji "github.com/superseriousbusiness/activity/streams/impl/toot/type_emoji"
	typehashtag "github.com/superseriousbusiness/activity/streams/impl/toot/type_hashtag"
	typeidentityproof "github.com/superseriousbusiness/activity/streams/impl/toot/type_identityproof"
	vocab "github.com/superseriousbusiness/activity/streams/vocab"
)

// TootEmojiIsDisjointWith returns true if Emoji is disjoint with the other's type.
func TootEmojiIsDisjointWith(other vocab.Type) bool {
	return typeemoji.EmojiIsDisjointWith(other)
}

// TootHashtagIsDisjointWith returns true if Hashtag is disjoint with the other's
// type.
func TootHashtagIsDisjointWith(other vocab.Type) bool {
	return typehashtag.HashtagIsDisjointWith(other)
}

// TootIdentityProofIsDisjointWith returns true if IdentityProof is disjoint with
// the other's type.
func TootIdentityProofIsDisjointWith(other vocab.Type) bool {
	return typeidentityproof.IdentityProofIsDisjointWith(other)
}
