// Code generated by mockery v2.7.4. DO NOT EDIT.

package media

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// MockMediaHandler is an autogenerated mock type for the MediaHandler type
type MockMediaHandler struct {
	mock.Mock
}

// SetHeaderForAccountID provides a mock function with given fields: f, id
func (_m *MockMediaHandler) SetHeaderForAccountID(f multipart.File, id string) (*HeaderInfo, error) {
	ret := _m.Called(f, id)

	var r0 *HeaderInfo
	if rf, ok := ret.Get(0).(func(multipart.File, string) *HeaderInfo); ok {
		r0 = rf(f, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*HeaderInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(multipart.File, string) error); ok {
		r1 = rf(f, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
