// Code generated by mockery v2.7.4. DO NOT EDIT.

package media

import mock "github.com/stretchr/testify/mock"

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}
