// Code generated by mockery v2.7.4. DO NOT EDIT.

package model

import mock "github.com/stretchr/testify/mock"

// MockFileMeta is an autogenerated mock type for the FileMeta type
type MockFileMeta struct {
	mock.Mock
}

// GetOriginal provides a mock function with given fields:
func (_m *MockFileMeta) GetOriginal() OriginalMeta {
	ret := _m.Called()

	var r0 OriginalMeta
	if rf, ok := ret.Get(0).(func() OriginalMeta); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(OriginalMeta)
		}
	}

	return r0
}

// GetSmall provides a mock function with given fields:
func (_m *MockFileMeta) GetSmall() SmallMeta {
	ret := _m.Called()

	var r0 SmallMeta
	if rf, ok := ret.Get(0).(func() SmallMeta); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SmallMeta)
		}
	}

	return r0
}
