// Code generated by mockery v2.7.4. DO NOT EDIT.

package distributor

import mock "github.com/stretchr/testify/mock"

// MockDistributor is an autogenerated mock type for the Distributor type
type MockDistributor struct {
	mock.Mock
}

// FromClientAPI provides a mock function with given fields:
func (_m *MockDistributor) FromClientAPI() chan FromClientAPI {
	ret := _m.Called()

	var r0 chan FromClientAPI
	if rf, ok := ret.Get(0).(func() chan FromClientAPI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan FromClientAPI)
		}
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *MockDistributor) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *MockDistributor) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToClientAPI provides a mock function with given fields:
func (_m *MockDistributor) ToClientAPI() chan ToClientAPI {
	ret := _m.Called()

	var r0 chan ToClientAPI
	if rf, ok := ret.Get(0).(func() chan ToClientAPI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan ToClientAPI)
		}
	}

	return r0
}
