// Code generated by mockery v2.7.4. DO NOT EDIT.

package module

import (
	mock "github.com/stretchr/testify/mock"
	router "github.com/superseriousbusiness/gotosocial/internal/router"
)

// MockClientAPIModule is an autogenerated mock type for the ClientAPIModule type
type MockClientAPIModule struct {
	mock.Mock
}

// Route provides a mock function with given fields: s
func (_m *MockClientAPIModule) Route(s router.Router) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(router.Router) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
