// Code generated by mockery v2.7.4. DO NOT EDIT.

package gotosocial

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGotosocial is an autogenerated mock type for the Gotosocial type
type MockGotosocial struct {
	mock.Mock
}

// Start provides a mock function with given fields: _a0
func (_m *MockGotosocial) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: _a0
func (_m *MockGotosocial) Stop(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
