// Code generated by MockGen. DO NOT EDIT.
// Source: pub/common_behavior.go

// Package pub is a generated GoMock package.
package pub

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	vocab "github.com/superseriousbusiness/activity/streams/vocab"
	http "net/http"
	url "net/url"
	reflect "reflect"
)

// MockCommonBehavior is a mock of CommonBehavior interface
type MockCommonBehavior struct {
	ctrl     *gomock.Controller
	recorder *MockCommonBehaviorMockRecorder
}

// MockCommonBehaviorMockRecorder is the mock recorder for MockCommonBehavior
type MockCommonBehaviorMockRecorder struct {
	mock *MockCommonBehavior
}

// NewMockCommonBehavior creates a new mock instance
func NewMockCommonBehavior(ctrl *gomock.Controller) *MockCommonBehavior {
	mock := &MockCommonBehavior{ctrl: ctrl}
	mock.recorder = &MockCommonBehaviorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommonBehavior) EXPECT() *MockCommonBehaviorMockRecorder {
	return m.recorder
}

// AuthenticateGetInbox mocks base method
func (m *MockCommonBehavior) AuthenticateGetInbox(c context.Context, w http.ResponseWriter, r *http.Request) (context.Context, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateGetInbox", c, w, r)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AuthenticateGetInbox indicates an expected call of AuthenticateGetInbox
func (mr *MockCommonBehaviorMockRecorder) AuthenticateGetInbox(c, w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateGetInbox", reflect.TypeOf((*MockCommonBehavior)(nil).AuthenticateGetInbox), c, w, r)
}

// AuthenticateGetOutbox mocks base method
func (m *MockCommonBehavior) AuthenticateGetOutbox(c context.Context, w http.ResponseWriter, r *http.Request) (context.Context, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateGetOutbox", c, w, r)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AuthenticateGetOutbox indicates an expected call of AuthenticateGetOutbox
func (mr *MockCommonBehaviorMockRecorder) AuthenticateGetOutbox(c, w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateGetOutbox", reflect.TypeOf((*MockCommonBehavior)(nil).AuthenticateGetOutbox), c, w, r)
}

// GetOutbox mocks base method
func (m *MockCommonBehavior) GetOutbox(c context.Context, r *http.Request) (vocab.ActivityStreamsOrderedCollectionPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutbox", c, r)
	ret0, _ := ret[0].(vocab.ActivityStreamsOrderedCollectionPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutbox indicates an expected call of GetOutbox
func (mr *MockCommonBehaviorMockRecorder) GetOutbox(c, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutbox", reflect.TypeOf((*MockCommonBehavior)(nil).GetOutbox), c, r)
}

// NewTransport mocks base method
func (m *MockCommonBehavior) NewTransport(c context.Context, actorBoxIRI *url.URL, gofedAgent string) (Transport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTransport", c, actorBoxIRI, gofedAgent)
	ret0, _ := ret[0].(Transport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewTransport indicates an expected call of NewTransport
func (mr *MockCommonBehaviorMockRecorder) NewTransport(c, actorBoxIRI, gofedAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTransport", reflect.TypeOf((*MockCommonBehavior)(nil).NewTransport), c, actorBoxIRI, gofedAgent)
}
