// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	router "github.com/superseriousbusiness/gotosocial/internal/router"
)

// ClientAPIModule is an autogenerated mock type for the ClientAPIModule type
type ClientAPIModule struct {
	mock.Mock
}

// Route provides a mock function with given fields: s
func (_m *ClientAPIModule) Route(s router.Router) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(router.Router) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
